;; -*- mode: fundamental -*-

(setq keyfreq-excluded-commands
      '(evil-insert
	evil-forward-char
	evil-normal-state
	self-insert-command
	my-quiet-save-buffer
	evil-forward-word-begin
	org-self-insert-command
	evil-backward-word-begin
	evil-better-visual-line-next-line
	evil-better-visual-line-previous-line
	last-buffer
	undo-tree-undo
	evil-backward-char
	ivy-next-line
	org-cycle
	org-delete-backward-char
	evil-next-visual-line
	markdown-outdent-or-delete
	hydra-commands/body
	abort-recursive-edit
	evil-org-delete
	ivy-backward-delete-char
	isearch-printing-char
	evil-paste-after
	quit-window
	evil-previous-visual-line
	evil-beginning-of-visual-line
	kill-this-buffer
	evil-visual-line
	ignore
	hydra-help/body
	my-below-line-macro
	evil-visual-char
	evil-ex-search-next
	evil-previous-line
	evil-next-line
	org-return
	evil-exit-visual-state
	ivy-previous-line
	evil-goto-first-line
	evil-delete
	backward-kill-word
	evil-goto-line
	hydra-find-emacs-files/body
	evil-ex-search-forward
	evil-org-append-line
	exit-minibuffer
	evil-forward-word-end
	my-paragraph-forward
	hydra-help/helpful-variable-and-exit
	evil-yank
	ivy-previous-history-element
	evil-destroy-change
	evil-delete-backward-char-and-join
	evil-org-delete-char
	org-forward-paragraph
	ivy-done
	org-hide-all
	evil-append
	hydra-commands/eval-src-block-and-exit
	hydra-help/helpful-key-and-exit
	my-quiet-save-buffer-markdown
	evil-replace
	evil-ex-delete-backward-char
	undo-tree-redo
	pdf-view-next-page
	c-down
	evil-change-line
	term-send-raw
	hydra-commands/eval-region-and-exit
	evil-delete-char
	org-backward-paragraph
	evil-org-open-below
	newline
	delete-backward-char
	hydra-text-main/body
	sentence-nav-evil-forward
	evil-forward-WORD-begin
	evil-append-line
	hydra-commands/hydra-tangle/body-and-exit
	c-up
	yas-next-field-or-maybe-expand
	ivy-dispatching-done-hydra
	recursive-narrow-or-widen-dwim
	evil-join
	c-electric-backspace
	evil-search-next
	my-paragraph-backwards
	evil-execute-macro
	forward-word
	scroll-up-command
	eyebrowse-next-window-config
	evil-jump-backward
	hydra-narrow/body
	tab-jump-out
	ivy-backward-kill-word
	hydra-find-file/body
	ivy-switch-buffer
	my-quiet-save-buffer-c
	evil-substitute
	comint-send-input
	company-ignore
	eyebrowse-prev-window-config
	kill-buffer-and-window
	previous-line
	sentence-nav-evil-backward
	evil-forward-WORD-end
	evil-search-forward
	handle-switch-frame
	windmove-right
	evil-record-macro
	pdf-view-previous-page
	hydra-prose/body
	yas-expand
	right-char
	hydra-window-resize/my/evil-dec-height
	hydra-modes/body
	next-line
	hydra-find-emacs-files/find-packs-and-exit
	org-toggle-latex-fragment
	hydra-find-emacs-files/find-keys-and-exit
	hydra-search/body
	windmove-left
	hydra-tangle/tangle-py-all-and-exit
	backward-delete-char-untabify
	ranger-next-file
	counsel-org-goto
	evil-visual-block
	evil-open-below
	recursive-widen
	ivy-scroll-up-command
	backward-word
	hydra-c-mode/execute-c-program-and-exit
	hydra-narrow/recursive-narrow-or-widen-dwim-and-exit
	markdown-enter-key
	evil-paste-pop
	ivy-read-action/lambda-w-and-exit
	evil-delete-line
	hydra-yasnippet/body
	evil-forward-sentence-begin
	hydra-find-emacs-files/find-functions-and-exit
	left-char
	scroll-down-command
	end-of-visual-line
	pdf-view-scroll-up-or-next-page
	ranger-prev-file
	org-edit-src-exit
	evil-goto-mark
	evil-backward-WORD-begin
	endless/ispell-word-then-abbrev
	my-flyspell-insert-word
	delete-window
	caps-lock-mode
	mark-whole-buffer
	hydra-window-resize/nil
	delete-other-windows
	isearch-exit
	org-edit-special
	hydra-window/body
	describe-key
	backward-button
	hydra-c-mode/body
	outline-show-all
	evil-paste-from-clipboard
	winner-undo
	evil-end-of-visual-line
	python-nav-forward-block
	hydra-text-main/hydra-text-commands/body-and-exit
	pabbrev-expand-maybe
	hydra-help/helpful-callable-and-exit
	python-nav-backward-block
	isearch-delete-char
	forward-button
	helm-next-line
	pdf-view-scroll-down-or-previous-page
	evil-backward-sentence-begin
	evil-set-marker
	python-nav-forward-statement
	evil-surround-region
	hydra-narrow/widenToCenter-and-exit
	org-insert-link
	eyebrowse-last-window-config
	clipboard-yank
	org-open-quiet
	hydra-find-file/find-scratch-markdown-and-exit
	hydra-quick-commands/body
	windmove-down
	evil-ex
	hydra-commands/eval-line-and-exit
	beginning-of-visual-line
	counsel-find-file
	indent-buffer
	ivy-scroll-down-command
	bs-cycle-next
	my-up-pdf-window
	sel-to-end
	widenToCenter
	hydra-window/hydra-window-resize/body-and-exit
	forward-sentence
	bs-cycle-previous
	hydra-find-emacs-files/find-hydras-and-exit
	ivy-read-action/lambda-h-and-exit
	show-server
	magit-invoke-popup-action
	markdown-backward-paragraph
	evil-commentary
	kill-word
	evil-jump-forward
	hydra-text-main/nil
	evil-mode
	delete-char
	windmove-up
	hydra-yasnippet/yas-visit-snippet-file-and-exit
	hydra-commands/i3-reload-and-exit
	tab-to-tab-stop
	hydra-modes/olivetti-mode-and-exit
	Info-next-reference
	my-markdown-forward-paragraph
	targets-inner-paragraph
	python-nav-backward-statement
	evil-sp-delete-line
	hydra-find-file/hydra-find-dotfiles/body-and-exit
	backward-sentence
	push-button
	company-select-next-or-abort
	ranger-close
	recenter-top-bottom
	hydra-commands/eval-buffer-and-exit
	c-electric-semi&comma
	hydra-yasnippet/yas-load-snippet-buffer-and-close-and-e
	org-backward-heading-same-level
	term-send-backspace
	org-delete-char
	company-complete
	ranger
	evil-find-char
	org-shiftup
	targets-a-paragraph
	hydra-text-main/copy-to-chrome-and-exit
	hydra-prose/hydra-flyspell/body-and-exit
	markdown-next-link
	backward-to-indentation
	olivetti-set-width
	org-up-element
	markdown-previous-link
	evil-scroll-page-down
	deft
	targets-inner-double-quote
	hydra-prose/hydra-langtool/body-and-exit
	evil-scroll-line-to-center
	profiler-report-next-entry
	hydra-text-main/duplicate-inner-paragraph-and-exit
	forward-to-indentation
	hydra-commands/hydra-more-commands/body-and-exit
	hydra-window-resize/body
	org-export-dispatch
	hippie-expand
	evil-digit-argument-or-evil-org-beginning-of-line
	keyboard-quit
	browse-kill-ring-forward
	org-end-of-line
	my-capitalize
	hydra-find-emacs-files/nil
	hydra-commands/nil
	hydra-find-dotfiles/find-i3-config-and-exit
	undefined
	ccm-mwheel-scroll
	evil-scroll-line-to-top
	hydra-org-mode/body
	hydra-search/helm-org-rifle-agenda-files-and-exit
	hydra-text-commands/create-setq-and-exit
	mwheel-scroll
	evil-indent
	evil-sp-change-line
	avy-goto-word-0-below
	kill-all-buffers
	my-ranger
	hydra-commands/tangle-and-eval-block-and-exit
	org-force-self-insert
	evil-mouse-drag-region
	evil-scroll-line-down
	helm-previous-line
	text-scale-adjust
	company-search-printing-char
	evil-jump-item
	previous-complete-history-element
	company-select-next
	whack-whitespace
	evil-ret
	magit-status
	hydra-search/counsel-grep-and-exit
	my-spc
	hydra-find-file/nil
	hydra-help/describe-package-and-exit
	evil-ex-search-previous
	evil-repeat
	profiler-report-previous-entry
	profiler-report-toggle-entry
	org-forward-heading-same-level
	hydra-pdf-view/my-pdf-prev-page-other-window
	hydra-find-file/my-find-scratch-buffer-and-exit
	evil-org-insert-line
	my-next-page-other-window
	targets-inner-word
	my-magit-commit
	hydra-search/nil
	evil-org-org-insert-heading-respect-content-below
	evil-use-register
	ranger-find-file
	evil-execute-in-god-state
	org-kill-line
	hydra-help/nil
	company-abort
	kmacro-start-macro-or-insert-counter
	with-editor-finish
	hydra-tangle/tangle-py-all-debug-and-exit
	hydra-org-clock/body
	evil-window-move-very-bottom
	quoted-insert
	disable-theme
	counsel-bookmark
	elmacro-show-last-macro
	evil-paste-before
	mouse-set-point
	hydra-help/show-major-mode-and-exit
	previous-history-element
	targets-a-paren
	backward-char
	hydra-yasnippet/yas-load-snippet-buffer-and-exit
	electric-pair-delete-pair
	evil-god-state-bail
	ranger-go
	my-quiet-save-buffer-python
	evil
	pdf-view-shrink
	evil-window-bottom
	markdown-export
	magit-push-popup
	define-global-abbrev
	hydra-modes/centered-cursor-mode-and-exit
	forward-char
	eyebrowse-switch-to-window-config-2
	hydra-text-main/duplicate-line-and-exit
	targets-inner-paren
	hydra-prose/prose-enable-and-exit
	abbrev-edit-save-buffer
	evil-insert-line
	minibuffer-keyboard-quit
	load-theme
	name-last-kbd-macro
	evil-window-top
	helm-maybe-exit-minibuffer
	evil-visual-restore
	hydra-pdf-view/body
	evil-fill-and-move
	my-term-botright
	org-next-link
	hydra-pdf-view/nil
	hydra-vertigo/body
	evil-scroll-line-up
	markdown-forward-paragraph
	hydra-prose/hydra-text-main/body-and-exit
	evil-digit-argument-or-evil-beginning-of-line
	org-ctrl-c-ret
	evil-previous-line-first-non-blank
	evil-paste-pop-next
        keyfreq-show
	keyfreq-reset))
