(setq buffer-expose-rescale-factor 0.6)
(setq buffer-expose-hide-regexes '(".*Log.*"
				   ".*log.*"
				   ".*help.*"
				   "^#.*#$"
				   "*Shell Command Output*"
				   "*Calculator*"
				   "*Calendar*"
				   "*Help*"
				   "*Calc Trail*"
				   "magit-process"
				   "magit-diff"
				   "*Org-Babel Error Output*"
				   "\\`\\*helm"
				   "\\`\\*Echo Area"
				   "\\`\\*Minibuf"
				   "Ibuffer"
				   "*Shell Command Output*"
				   "*Calculator*"
				   "*Calendar*"
				   "*cheatsheet*"
				   "*Help*"
				   "*Echo Area 0*"
				   "*Echo Area 1"
				   "*Minibuf 0*"
				   "bookmark-default.el"
				   "info-history"
				   "company-shell-autoloads.el"
				   "company.el"
				   "pos-tip-autoloads.el"
				   "*Warning*"
				   "*Messages*"
				   "*Flycheck error messages*"
				   "*company-documentation*"
				   "^.archive.org$"
				   ".*magit.*"
				   ".*elc"
				   "*shell*"
				   "*new*"
				   "*Flycheck error messages*"
				   "*clang-output*"
				   "*Bongo Playlist*"
				   "*eclim: problems*"
				   "*eclimd*"
				   "*compilation*"))
