#!/bin/bash

i3-msg [title="term-ranger"] move scratchpad
i3-msg [class="Hexchat"] move scratchpad
i3-msg [class="SpeedCrunch"] move scratchpad
i3-msg [class="Xfce4-taskmanager"] move scratchpad
i3-msg [title="term-music"] move scratchpad
