#!/bin/bash

i3-msg [class=sranger] move scratchpad > /dev/null 2>&1 &
i3-msg [class=scratchterm] move scratchpad > /dev/null 2>&1 &
i3-msg [class='Emacs'] focus > /dev/null 2>&1 &
emacsclient --socket-name=gui-emacs --create-frame --no-wait --alternate-editor="" --eval "(find-temp-markdown)" > /dev/null 2>&1 &
