(setq projectile-globally-ignored-files '(".*Log.*"
				   ".*log.*"
				   ".*help.*"
				   "^#.*#$"
				   "*Shell Command Output*"
				   "*Calculator*"
				   "*Calendar*"
				   "*Help*"
				   "*Calc Trail*"
				   "magit-process"
				   "magit-diff"
				   "*Org-Babel Error Output*"
				   "\\`\\*helm"
				   "\\`\\*Echo Area"
				   "\\`\\*Minibuf"
				   "Ibuffer"
				   "*Shell Command Output*"
				   "*Calculator*"
				   "*Calendar*"
				   "*cheatsheet*"
				   "*Help*"
				   "*Echo Area 0*"
				   "*Echo Area 1"
				   "*Minibuf 0*"
				   "bookmark-default.el"
				   "info-history"
				   "company-shell-autoloads.el"
				   "company.el"
				   "pos-tip-autoloads.el"
				   "*scratch*"
				   "*Warning*"
				   "*Messages*"
				   "^init.org$"
				   "^packs.org$"
				   "^functions.org$"
				   "^keys.org$"
				   "^misc.org$"
				   "^macros.org$"
				   "^hydras.org$"
				   "^links.org$"
				   "^custom.el$"
				   "*Flycheck error messages*"
				   "*Flymake log*"
				   "*company-documentation*"
				   "^.archive.org$"
				   ".*magit.*"
				   ".*elc"
				   "*shell*"
				   "*new*"
				   "*Flycheck error messages*"
				   "*clang-output*"
				   "*Bongo Playlist*"
				   "*eclim: problems*"
				   "*eclimd*"
				   "*compilation*"
				   "*Bongo Library*"))
