 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
package java.time;
public enum DayOfWeek implements java.time.temporal.TemporalAccessor, java.time.temporal.TemporalAdjuster {
  
  MONDAY(),
  
  TUESDAY(),
  
  WEDNESDAY(),
  
  THURSDAY(),
  
  FRIDAY(),
  
  SATURDAY(),
  
  SUNDAY(),;
  
  private static final java.time.DayOfWeek[] ENUMS;
  
  private static final java.time.DayOfWeek[] $VALUES;
  
  private DayOfWeek(ayOfWeek(java.lang.String arg0, int arg1) {
  }
  
  public static java.time.DayOfWeek of(int arg0) {
    return null;
  }
  
  public static java.time.DayOfWeek from(java.time.temporal.TemporalAccessor arg0) {
    return null;
  }
  
  public int getValue() {
    return 0;
  }
  
  public java.lang.String getDisplayName(java.time.format.TextStyle arg0, java.util.Locale arg1) {
    return null;
  }
  
  public boolean isSupported(java.time.temporal.TemporalField arg0) {
    return false;
  }
  
  public java.time.temporal.ValueRange range(java.time.temporal.TemporalField arg0) {
    return null;
  }
  
  public int get(java.time.temporal.TemporalField arg0) {
    return 0;
  }
  
  public long getLong(java.time.temporal.TemporalField arg0) {
    return 0;
  }
  
  public java.time.DayOfWeek plus(long arg0) {
    return null;
  }
  
  public java.time.DayOfWeek minus(long arg0) {
    return null;
  }
  
  public <R> R query(java.time.temporal.TemporalQuery<R> arg0) {
    return null;
  }
  
  public java.time.temporal.Temporal adjustInto(java.time.temporal.Temporal arg0) {
    return null;
  }
}