#!/usr/bin/env bash
 
echo "# py-text-adventure" >> README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin git@github.com:mrbig033/py-text-adventure.git
git push -u origin master
