(setq ivy-ignore-buffers '(".*Log.*"
			   ".*log.*"
			   ".*help.*"
			   "^#.*#$"
			   "*Shell Command Output*"
			   "*Calculator*"
			   "*Calendar*"
			   "*Help*"
			   "*Calc Trail*"
			   "magit-process"
			   "magit-diff"
			   "*Org-Babel Error Output*"
			   "\\`\\*helm"
			   "\\`\\*Echo Area"
			   "\\`\\*Minibuf"
			   "Ibuffer"
			   "*cheatsheet*"
			   "*Echo Area 0*"
			   "*Echo Area 1"
			   "*Minibuf 0*"
			   "bookmark-default.el"
			   "info-history"
			   "company-shell-autoloads.el"
			   "company.el"
			   "pos-tip-autoloads.el"
			   "*Flycheck error messages*"
			   "*company-documentation*"
			   "^.archive.org$"
			   ".*magit.*"
			   ".*elc"
			   "*Bongo Playlist*"
			   "*Bongo Library*"
			   "text_scratch"
			   "markdown_scratch"
			   "fundamental_scratch"
			   "org_scratch"
			   "prog_scratch"
			   "*scratch*"
			   "*Warning*"
			   "*Messages*"
			   "i3keys.org"
			   "info_keys.org"))
