(which-key-add-key-based-replacements
  "C-c C-j" "journal"
  "C-c M-g" "magit popup"
  "C-c w" "evil window"
  "C-c L" "load stuff"
  "C-c f" "filesets"
  "C-c f e" "edit"
  "C-c f c" "close"
  "C-c f o" "open"
  "C-c C-s" "md code"
  "C-c m" "modes"
  "C-c m e" "evil"
  "C-c m g" "writegood"
  "C-c m w" "which-key"
  "C-c l" "load"
  "C-c u" "load"
  "C-c i" "editing"
  "C-c e" "evil commands"
  "C-c b" "buffers"
  "C-c b" "commands"
  "C-c o" "org"
  "C-c C-v" "babel"
  "C-c C-x" "org extras"
  "C-c &" "yasnippet"
  "C-c \"" "org plot"
  "C-c q" "filling"
  "C-c q j" "justify"
  "C-c q f" "fit"
  "C-c q f" "fit"
  "C-c q j 5" "just 59"
  "C-c q j 7" "just 79"
  "C-c q j 8" "just 85"
  "C-c q j 9" "just 95"
  "C-c q j 0" "just 100"
  "C-c q f 5" "fit  59"
  "C-c q f 7" "fit  79"
  "C-c q f 8" "fit  85"
  "C-c q f 9" "fit  95"
  "C-c q f 0" "fit  100"
  "C-c q a" "fill mode"
  "C-c q g" "agg par mode"
  "C-c m g g"  "writegood mode"
  "C-c m g e" "writegood reading ease"
  "C-c m 2" "org2blog"
  "C-c m 2 b" "wp buffer"
  "C-c m 2 b p" "post draft"
  "C-c m 2 b u" "publish"
  "C-c m 2 s" "wp subtree"
  "C-c m 2 s p" "post draft"
  "C-c m 2 s u" "publish"
  "C-c m 2 l" "wp login"
  "C-c m 2 o" "wp logout"
  "C-c m 2 n" "wp new")
